### ISSUE TITLE
How did you compile?

### ISSUE THREAD

**Issue by CoinLogik** [xbbricker/ccminer-cryptonight-mac#7]
I cannot get original src to compile on macOS. I would love any advice you could share.

**Comment by fireheadman** [comment]
Here's what I got  (hopefully it helps)...    
NOTE:  I have tried xmr-stak and xmrig for GPU (neither would compile)..   Thankful I have this working since I hate booting into windows (bootcamp) just to mine.    
BTW:  I am using an eGPU I built with a 1060 3GB SC EVGA card.   Mining and still using 3 monitors for daily use.... oh and also have the CPUs mining with xmr-stak

```
git clone -b mac https://github.com/xbbricker/ccminer-cryptonight-mac
cd ccminer-cryptonight-mac/
./autogen.sh
./configure
make
```

Other info:
OS Version is 10.13.3

```
[fireheadman@demon miner 3105]$ clang --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

[fireheadman@demon miner 3099]$ /Developer/NVIDIA/CUDA-9.1/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Tue_Dec_19_21:36:29_CST_2017
Cuda compilation tools, release 9.1, V9.1.128
```

config.json   (-c config.json)
```
{
	"algo":  "cryptonight",
	"url":  "stratum+tcp://pool.supportxmr.com:3333",
	"user":  "YOUR ADDRESS HERE",
	"pass":  "rig1000:x",
	"keepalive":   true,
	"bfactor":   8,
	"bsleep":   50
	
}
```

**Comment by fireheadman** [comment]
one thing I wish would work is "Background" option and ability to Log output

**Comment by xbbricker** [comment]
Closing since instructions are included in the README.
